[package]
name = "gtk_liststore_item"
version = "0.1.0"
authors = ["Romain Porte <microjoe@microjoe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.*"
gtk_liststore_item_derive = { version = "0.1.0", optional = true, path = "../gtk_liststore_item_derive" }

[dev-dependencies]
gladis = "0.2.*"
gladis_proc_macro = "0.2.*"
gtk_liststore_item_derive = { version = "0.1.*", path = "../gtk_liststore_item_derive" }

[features]
default = []
derive = ["gtk_liststore_item_derive"]
